package modelo;

// Generated 13-dic-2011 23:21:03 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AfeccionJugador generated by hbm2java
 */
@Entity
@Table(name = "afeccion_jugador")
public class AfeccionJugador implements java.io.Serializable {

	private AfeccionJugadorId id;
	private DatoMedico datoMedico;
	private TipoAfeccion tipoAfeccion;
	private char estatus;

	public AfeccionJugador() {
	}

	public AfeccionJugador(AfeccionJugadorId id, DatoMedico datoMedico,
			TipoAfeccion tipoAfeccion, char estatus) {
		this.id = id;
		this.datoMedico = datoMedico;
		this.tipoAfeccion = tipoAfeccion;
		this.estatus = estatus;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoDatoMedico", column = @Column(name = "codigo_dato_medico", nullable = false)),
			@AttributeOverride(name = "codigoAfeccion", column = @Column(name = "codigo_afeccion", nullable = false)) })
	public AfeccionJugadorId getId() {
		return this.id;
	}

	public void setId(AfeccionJugadorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_dato_medico", nullable = false, insertable = false, updatable = false)
	public DatoMedico getDatoMedico() {
		return this.datoMedico;
	}

	public void setDatoMedico(DatoMedico datoMedico) {
		this.datoMedico = datoMedico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_afeccion", nullable = false, insertable = false, updatable = false)
	public TipoAfeccion getTipoAfeccion() {
		return this.tipoAfeccion;
	}

	public void setTipoAfeccion(TipoAfeccion tipoAfeccion) {
		this.tipoAfeccion = tipoAfeccion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

}
