package modelo;

// Generated 16-dic-2011 17:19:16 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AfeccionJugadorId generated by hbm2java
 */
@Embeddable
public class AfeccionJugadorId implements java.io.Serializable {

	private String codigoDatoMedico;
	private String codigoAfeccion;

	public AfeccionJugadorId() {
	}

	public AfeccionJugadorId(String codigoDatoMedico, String codigoAfeccion) {
		this.codigoDatoMedico = codigoDatoMedico;
		this.codigoAfeccion = codigoAfeccion;
	}

	@Column(name = "codigo_dato_medico", nullable = false)
	public String getCodigoDatoMedico() {
		return this.codigoDatoMedico;
	}

	public void setCodigoDatoMedico(String codigoDatoMedico) {
		this.codigoDatoMedico = codigoDatoMedico;
	}

	@Column(name = "codigo_afeccion", nullable = false)
	public String getCodigoAfeccion() {
		return this.codigoAfeccion;
	}

	public void setCodigoAfeccion(String codigoAfeccion) {
		this.codigoAfeccion = codigoAfeccion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AfeccionJugadorId))
			return false;
		AfeccionJugadorId castOther = (AfeccionJugadorId) other;

		return ((this.getCodigoDatoMedico() == castOther.getCodigoDatoMedico()) || (this
				.getCodigoDatoMedico() != null
				&& castOther.getCodigoDatoMedico() != null && this
				.getCodigoDatoMedico().equals(castOther.getCodigoDatoMedico())))
				&& ((this.getCodigoAfeccion() == castOther.getCodigoAfeccion()) || (this
						.getCodigoAfeccion() != null
						&& castOther.getCodigoAfeccion() != null && this
						.getCodigoAfeccion().equals(
								castOther.getCodigoAfeccion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodigoDatoMedico() == null ? 0 : this
						.getCodigoDatoMedico().hashCode());
		result = 37
				* result
				+ (getCodigoAfeccion() == null ? 0 : this.getCodigoAfeccion()
						.hashCode());
		return result;
	}

}
