package modelo;

// Generated 16-dic-2011 17:19:16 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ComisionEquipoId generated by hbm2java
 */
@Embeddable
public class ComisionEquipoId implements java.io.Serializable {

	private String codigoEquipo;
	private String codigoClasificacion;

	public ComisionEquipoId() {
	}

	public ComisionEquipoId(String codigoEquipo, String codigoClasificacion) {
		this.codigoEquipo = codigoEquipo;
		this.codigoClasificacion = codigoClasificacion;
	}

	@Column(name = "codigo_equipo", nullable = false)
	public String getCodigoEquipo() {
		return this.codigoEquipo;
	}

	public void setCodigoEquipo(String codigoEquipo) {
		this.codigoEquipo = codigoEquipo;
	}

	@Column(name = "codigo_clasificacion", nullable = false)
	public String getCodigoClasificacion() {
		return this.codigoClasificacion;
	}

	public void setCodigoClasificacion(String codigoClasificacion) {
		this.codigoClasificacion = codigoClasificacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ComisionEquipoId))
			return false;
		ComisionEquipoId castOther = (ComisionEquipoId) other;

		return ((this.getCodigoEquipo() == castOther.getCodigoEquipo()) || (this
				.getCodigoEquipo() != null
				&& castOther.getCodigoEquipo() != null && this
				.getCodigoEquipo().equals(castOther.getCodigoEquipo())))
				&& ((this.getCodigoClasificacion() == castOther
						.getCodigoClasificacion()) || (this
						.getCodigoClasificacion() != null
						&& castOther.getCodigoClasificacion() != null && this
						.getCodigoClasificacion().equals(
								castOther.getCodigoClasificacion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodigoEquipo() == null ? 0 : this.getCodigoEquipo()
						.hashCode());
		result = 37
				* result
				+ (getCodigoClasificacion() == null ? 0 : this
						.getCodigoClasificacion().hashCode());
		return result;
	}

}
