package modelo;

// Generated 13-dic-2011 23:21:03 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatoAcademico generated by hbm2java
 */
@Entity
@Table(name = "dato_academico")
public class DatoAcademico implements java.io.Serializable {

	private String codigoAcademico;
	private Institucion institucion;
	private Jugador jugador;
	private Curso curso;
	private AnnoEscolar annoEscolar;
	private Date fechaIngreso;
	private char estatus;
	private Set<DocumentoAcademico> documentoAcademicos = new HashSet<DocumentoAcademico>(
			0);

	public DatoAcademico() {
	}

	public DatoAcademico(String codigoAcademico, Institucion institucion,
			Jugador jugador, Curso curso, AnnoEscolar annoEscolar,
			Date fechaIngreso, char estatus) {
		this.codigoAcademico = codigoAcademico;
		this.institucion = institucion;
		this.jugador = jugador;
		this.curso = curso;
		this.annoEscolar = annoEscolar;
		this.fechaIngreso = fechaIngreso;
		this.estatus = estatus;
	}

	public DatoAcademico(String codigoAcademico, Institucion institucion,
			Jugador jugador, Curso curso, AnnoEscolar annoEscolar,
			Date fechaIngreso, char estatus,
			Set<DocumentoAcademico> documentoAcademicos) {
		this.codigoAcademico = codigoAcademico;
		this.institucion = institucion;
		this.jugador = jugador;
		this.curso = curso;
		this.annoEscolar = annoEscolar;
		this.fechaIngreso = fechaIngreso;
		this.estatus = estatus;
		this.documentoAcademicos = documentoAcademicos;
	}

	@Id
	@Column(name = "codigo_academico", unique = true, nullable = false)
	public String getCodigoAcademico() {
		return this.codigoAcademico;
	}

	public void setCodigoAcademico(String codigoAcademico) {
		this.codigoAcademico = codigoAcademico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_institucion", nullable = false)
	public Institucion getInstitucion() {
		return this.institucion;
	}

	public void setInstitucion(Institucion institucion) {
		this.institucion = institucion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cedula_jugador", nullable = false)
	public Jugador getJugador() {
		return this.jugador;
	}

	public void setJugador(Jugador jugador) {
		this.jugador = jugador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_curso", nullable = false)
	public Curso getCurso() {
		return this.curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_anno_escolar", nullable = false)
	public AnnoEscolar getAnnoEscolar() {
		return this.annoEscolar;
	}

	public void setAnnoEscolar(AnnoEscolar annoEscolar) {
		this.annoEscolar = annoEscolar;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ingreso", nullable = false, length = 13)
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "datoAcademico")
	public Set<DocumentoAcademico> getDocumentoAcademicos() {
		return this.documentoAcademicos;
	}

	public void setDocumentoAcademicos(
			Set<DocumentoAcademico> documentoAcademicos) {
		this.documentoAcademicos = documentoAcademicos;
	}

}
