package modelo;

// Generated 16-dic-2011 17:19:16 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * DesempennoColectivo generated by hbm2java
 */
@Entity
@Table(name = "desempenno_colectivo")
public class DesempennoColectivo implements java.io.Serializable {

	private String codigoEquipoJuego;
	private EquipoJuego equipoJuego;
	private int valor;
	private int inning;

	public DesempennoColectivo() {
	}

	public DesempennoColectivo(EquipoJuego equipoJuego, int valor, int inning) {
		this.equipoJuego = equipoJuego;
		this.valor = valor;
		this.inning = inning;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "equipoJuego"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "codigo_equipo_juego", unique = true, nullable = false)
	public String getCodigoEquipoJuego() {
		return this.codigoEquipoJuego;
	}

	public void setCodigoEquipoJuego(String codigoEquipoJuego) {
		this.codigoEquipoJuego = codigoEquipoJuego;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public EquipoJuego getEquipoJuego() {
		return this.equipoJuego;
	}

	public void setEquipoJuego(EquipoJuego equipoJuego) {
		this.equipoJuego = equipoJuego;
	}

	@Column(name = "valor", nullable = false)
	public int getValor() {
		return this.valor;
	}

	public void setValor(int valor) {
		this.valor = valor;
	}

	@Column(name = "inning", nullable = false)
	public int getInning() {
		return this.inning;
	}

	public void setInning(int inning) {
		this.inning = inning;
	}

}
