package modelo;

// Generated 17/12/2011 10:20:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DocumentoAscensoId generated by hbm2java
 */
@Embeddable
public class DocumentoAscensoId implements java.io.Serializable {

	private String codigoDocumentoEntregado;
	private String codigoAscenso;

	public DocumentoAscensoId() {
	}

	public DocumentoAscensoId(String codigoDocumentoEntregado,
			String codigoAscenso) {
		this.codigoDocumentoEntregado = codigoDocumentoEntregado;
		this.codigoAscenso = codigoAscenso;
	}

	@Column(name = "codigo_documento_entregado", nullable = false)
	public String getCodigoDocumentoEntregado() {
		return this.codigoDocumentoEntregado;
	}

	public void setCodigoDocumentoEntregado(String codigoDocumentoEntregado) {
		this.codigoDocumentoEntregado = codigoDocumentoEntregado;
	}

	@Column(name = "codigo_ascenso", nullable = false)
	public String getCodigoAscenso() {
		return this.codigoAscenso;
	}

	public void setCodigoAscenso(String codigoAscenso) {
		this.codigoAscenso = codigoAscenso;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DocumentoAscensoId))
			return false;
		DocumentoAscensoId castOther = (DocumentoAscensoId) other;

		return ((this.getCodigoDocumentoEntregado() == castOther
				.getCodigoDocumentoEntregado()) || (this
				.getCodigoDocumentoEntregado() != null
				&& castOther.getCodigoDocumentoEntregado() != null && this
				.getCodigoDocumentoEntregado().equals(
						castOther.getCodigoDocumentoEntregado())))
				&& ((this.getCodigoAscenso() == castOther.getCodigoAscenso()) || (this
						.getCodigoAscenso() != null
						&& castOther.getCodigoAscenso() != null && this
						.getCodigoAscenso()
						.equals(castOther.getCodigoAscenso())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodigoDocumentoEntregado() == null ? 0 : this
						.getCodigoDocumentoEntregado().hashCode());
		result = 37
				* result
				+ (getCodigoAscenso() == null ? 0 : this.getCodigoAscenso()
						.hashCode());
		return result;
	}

}
