package modelo;

// Generated 13-dic-2011 21:15:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DocumentoMedicoId generated by hbm2java
 */
@Embeddable
public class DocumentoMedicoId implements java.io.Serializable {

	private String codigoDatoMedico;
	private String codigoDocumentoEntregado;

	public DocumentoMedicoId() {
	}

	public DocumentoMedicoId(String codigoDatoMedico,
			String codigoDocumentoEntregado) {
		this.codigoDatoMedico = codigoDatoMedico;
		this.codigoDocumentoEntregado = codigoDocumentoEntregado;
	}

	@Column(name = "codigo_dato_medico", nullable = false)
	public String getCodigoDatoMedico() {
		return this.codigoDatoMedico;
	}

	public void setCodigoDatoMedico(String codigoDatoMedico) {
		this.codigoDatoMedico = codigoDatoMedico;
	}

	@Column(name = "codigo_documento_entregado", nullable = false)
	public String getCodigoDocumentoEntregado() {
		return this.codigoDocumentoEntregado;
	}

	public void setCodigoDocumentoEntregado(String codigoDocumentoEntregado) {
		this.codigoDocumentoEntregado = codigoDocumentoEntregado;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DocumentoMedicoId))
			return false;
		DocumentoMedicoId castOther = (DocumentoMedicoId) other;

		return ((this.getCodigoDatoMedico() == castOther.getCodigoDatoMedico()) || (this
				.getCodigoDatoMedico() != null
				&& castOther.getCodigoDatoMedico() != null && this
				.getCodigoDatoMedico().equals(castOther.getCodigoDatoMedico())))
				&& ((this.getCodigoDocumentoEntregado() == castOther
						.getCodigoDocumentoEntregado()) || (this
						.getCodigoDocumentoEntregado() != null
						&& castOther.getCodigoDocumentoEntregado() != null && this
						.getCodigoDocumentoEntregado().equals(
								castOther.getCodigoDocumentoEntregado())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodigoDatoMedico() == null ? 0 : this
						.getCodigoDatoMedico().hashCode());
		result = 37
				* result
				+ (getCodigoDocumentoEntregado() == null ? 0 : this
						.getCodigoDocumentoEntregado().hashCode());
		return result;
	}

}
