package modelo;

// Generated 09/01/2012 10:19:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EgresoCuentaPagarId generated by hbm2java
 */
@Embeddable
public class EgresoCuentaPagarId implements java.io.Serializable {

	private String numeroDocumento;
	private String origen;

	public EgresoCuentaPagarId() {
	}

	public EgresoCuentaPagarId(String numeroDocumento, String origen) {
		this.numeroDocumento = numeroDocumento;
		this.origen = origen;
	}

	@Column(name = "numero_documento", nullable = false)
	public String getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	@Column(name = "origen", nullable = false)
	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EgresoCuentaPagarId))
			return false;
		EgresoCuentaPagarId castOther = (EgresoCuentaPagarId) other;

		return ((this.getNumeroDocumento() == castOther.getNumeroDocumento()) || (this
				.getNumeroDocumento() != null
				&& castOther.getNumeroDocumento() != null && this
				.getNumeroDocumento().equals(castOther.getNumeroDocumento())))
				&& ((this.getOrigen() == castOther.getOrigen()) || (this
						.getOrigen() != null && castOther.getOrigen() != null && this
						.getOrigen().equals(castOther.getOrigen())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getNumeroDocumento() == null ? 0 : this.getNumeroDocumento()
						.hashCode());
		result = 37 * result
				+ (getOrigen() == null ? 0 : this.getOrigen().hashCode());
		return result;
	}

}
