package modelo;

// Generated 16-dic-2011 17:19:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estadio generated by hbm2java
 */
@Entity
@Table(name = "estadio")
public class Estadio implements java.io.Serializable {

	private String codigoEstadio;
	private DatoBasico datoBasico;
	private String nombre;
	private String direccion;
	private Set<Juego> juegos = new HashSet<Juego>(0);

	public Estadio() {
	}

	public Estadio(String codigoEstadio, DatoBasico datoBasico, String nombre,
			String direccion) {
		this.codigoEstadio = codigoEstadio;
		this.datoBasico = datoBasico;
		this.nombre = nombre;
		this.direccion = direccion;
	}

	public Estadio(String codigoEstadio, DatoBasico datoBasico, String nombre,
			String direccion, Set<Juego> juegos) {
		this.codigoEstadio = codigoEstadio;
		this.datoBasico = datoBasico;
		this.nombre = nombre;
		this.direccion = direccion;
		this.juegos = juegos;
	}

	@Id
	@Column(name = "codigo_estadio", unique = true, nullable = false)
	public String getCodigoEstadio() {
		return this.codigoEstadio;
	}

	public void setCodigoEstadio(String codigoEstadio) {
		this.codigoEstadio = codigoEstadio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_parroquia", nullable = false)
	public DatoBasico getDatoBasico() {
		return this.datoBasico;
	}

	public void setDatoBasico(DatoBasico datoBasico) {
		this.datoBasico = datoBasico;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "direccion", nullable = false)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadio")
	public Set<Juego> getJuegos() {
		return this.juegos;
	}

	public void setJuegos(Set<Juego> juegos) {
		this.juegos = juegos;
	}

}
