package modelo;

// Generated 22-dic-2011 17:58:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FamiliarComisionEquipoId generated by hbm2java
 */
@Embeddable
public class FamiliarComisionEquipoId implements java.io.Serializable {

	private int codigoFamiliarJugador;
	private int codigoComisionEquipo;

	public FamiliarComisionEquipoId() {
	}

	public FamiliarComisionEquipoId(int codigoFamiliarJugador,
			int codigoComisionEquipo) {
		this.codigoFamiliarJugador = codigoFamiliarJugador;
		this.codigoComisionEquipo = codigoComisionEquipo;
	}

	@Column(name = "codigo_familiar_jugador", nullable = false)
	public int getCodigoFamiliarJugador() {
		return this.codigoFamiliarJugador;
	}

	public void setCodigoFamiliarJugador(int codigoFamiliarJugador) {
		this.codigoFamiliarJugador = codigoFamiliarJugador;
	}

	@Column(name = "codigo_comision_equipo", nullable = false)
	public int getCodigoComisionEquipo() {
		return this.codigoComisionEquipo;
	}

	public void setCodigoComisionEquipo(int codigoComisionEquipo) {
		this.codigoComisionEquipo = codigoComisionEquipo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FamiliarComisionEquipoId))
			return false;
		FamiliarComisionEquipoId castOther = (FamiliarComisionEquipoId) other;

		return (this.getCodigoFamiliarJugador() == castOther
				.getCodigoFamiliarJugador())
				&& (this.getCodigoComisionEquipo() == castOther
						.getCodigoComisionEquipo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoFamiliarJugador();
		result = 37 * result + this.getCodigoComisionEquipo();
		return result;
	}

}
