package modelo;

// Generated 17/12/2011 10:20:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FamiliarComisionEquipoId generated by hbm2java
 */
@Embeddable
public class FamiliarComisionEquipoId implements java.io.Serializable {

	private String codigoEquipo;
	private String codigoComision;
	private String cedulaRif;
	private String cedulaFamiliar;

	public FamiliarComisionEquipoId() {
	}

	public FamiliarComisionEquipoId(String codigoEquipo, String codigoComision,
			String cedulaRif, String cedulaFamiliar) {
		this.codigoEquipo = codigoEquipo;
		this.codigoComision = codigoComision;
		this.cedulaRif = cedulaRif;
		this.cedulaFamiliar = cedulaFamiliar;
	}

	@Column(name = "codigo_equipo", nullable = false)
	public String getCodigoEquipo() {
		return this.codigoEquipo;
	}

	public void setCodigoEquipo(String codigoEquipo) {
		this.codigoEquipo = codigoEquipo;
	}

	@Column(name = "codigo_comision", nullable = false)
	public String getCodigoComision() {
		return this.codigoComision;
	}

	public void setCodigoComision(String codigoComision) {
		this.codigoComision = codigoComision;
	}

	@Column(name = "cedula_rif", nullable = false)
	public String getCedulaRif() {
		return this.cedulaRif;
	}

	public void setCedulaRif(String cedulaRif) {
		this.cedulaRif = cedulaRif;
	}

	@Column(name = "cedula_familiar", nullable = false)
	public String getCedulaFamiliar() {
		return this.cedulaFamiliar;
	}

	public void setCedulaFamiliar(String cedulaFamiliar) {
		this.cedulaFamiliar = cedulaFamiliar;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FamiliarComisionEquipoId))
			return false;
		FamiliarComisionEquipoId castOther = (FamiliarComisionEquipoId) other;

		return ((this.getCodigoEquipo() == castOther.getCodigoEquipo()) || (this
				.getCodigoEquipo() != null
				&& castOther.getCodigoEquipo() != null && this
				.getCodigoEquipo().equals(castOther.getCodigoEquipo())))
				&& ((this.getCodigoComision() == castOther.getCodigoComision()) || (this
						.getCodigoComision() != null
						&& castOther.getCodigoComision() != null && this
						.getCodigoComision().equals(
								castOther.getCodigoComision())))
				&& ((this.getCedulaRif() == castOther.getCedulaRif()) || (this
						.getCedulaRif() != null
						&& castOther.getCedulaRif() != null && this
						.getCedulaRif().equals(castOther.getCedulaRif())))
				&& ((this.getCedulaFamiliar() == castOther.getCedulaFamiliar()) || (this
						.getCedulaFamiliar() != null
						&& castOther.getCedulaFamiliar() != null && this
						.getCedulaFamiliar().equals(
								castOther.getCedulaFamiliar())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodigoEquipo() == null ? 0 : this.getCodigoEquipo()
						.hashCode());
		result = 37
				* result
				+ (getCodigoComision() == null ? 0 : this.getCodigoComision()
						.hashCode());
		result = 37 * result
				+ (getCedulaRif() == null ? 0 : this.getCedulaRif().hashCode());
		result = 37
				* result
				+ (getCedulaFamiliar() == null ? 0 : this.getCedulaFamiliar()
						.hashCode());
		return result;
	}

}
