package modelo;

// Generated 13-dic-2011 23:21:03 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HospedajeJudadorId generated by hbm2java
 */
@Embeddable
public class HospedajeJudadorId implements java.io.Serializable {

	private String codigoHospedaje;
	private String cedulaJugador;
	private String cedulaFamiliar;

	public HospedajeJudadorId() {
	}

	public HospedajeJudadorId(String codigoHospedaje, String cedulaJugador,
			String cedulaFamiliar) {
		this.codigoHospedaje = codigoHospedaje;
		this.cedulaJugador = cedulaJugador;
		this.cedulaFamiliar = cedulaFamiliar;
	}

	@Column(name = "codigo_hospedaje", nullable = false)
	public String getCodigoHospedaje() {
		return this.codigoHospedaje;
	}

	public void setCodigoHospedaje(String codigoHospedaje) {
		this.codigoHospedaje = codigoHospedaje;
	}

	@Column(name = "cedula_jugador", nullable = false)
	public String getCedulaJugador() {
		return this.cedulaJugador;
	}

	public void setCedulaJugador(String cedulaJugador) {
		this.cedulaJugador = cedulaJugador;
	}

	@Column(name = "cedula_familiar", nullable = false)
	public String getCedulaFamiliar() {
		return this.cedulaFamiliar;
	}

	public void setCedulaFamiliar(String cedulaFamiliar) {
		this.cedulaFamiliar = cedulaFamiliar;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HospedajeJudadorId))
			return false;
		HospedajeJudadorId castOther = (HospedajeJudadorId) other;

		return ((this.getCodigoHospedaje() == castOther.getCodigoHospedaje()) || (this
				.getCodigoHospedaje() != null
				&& castOther.getCodigoHospedaje() != null && this
				.getCodigoHospedaje().equals(castOther.getCodigoHospedaje())))
				&& ((this.getCedulaJugador() == castOther.getCedulaJugador()) || (this
						.getCedulaJugador() != null
						&& castOther.getCedulaJugador() != null && this
						.getCedulaJugador()
						.equals(castOther.getCedulaJugador())))
				&& ((this.getCedulaFamiliar() == castOther.getCedulaFamiliar()) || (this
						.getCedulaFamiliar() != null
						&& castOther.getCedulaFamiliar() != null && this
						.getCedulaFamiliar().equals(
								castOther.getCedulaFamiliar())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodigoHospedaje() == null ? 0 : this.getCodigoHospedaje()
						.hashCode());
		result = 37
				* result
				+ (getCedulaJugador() == null ? 0 : this.getCedulaJugador()
						.hashCode());
		result = 37
				* result
				+ (getCedulaFamiliar() == null ? 0 : this.getCedulaFamiliar()
						.hashCode());
		return result;
	}

}
