package modelo;

// Generated 13-dic-2011 21:15:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Hospedaje generated by hbm2java
 */
@Entity
@Table(name = "hospedaje")
public class Hospedaje implements java.io.Serializable {

	private HospedajeId id;
	private Competencia competencia;
	private FamiliarJugador familiarJugador;
	private char estatus;
	private HospedajeJudador hospedajeJudador;

	public Hospedaje() {
	}

	public Hospedaje(HospedajeId id, Competencia competencia,
			FamiliarJugador familiarJugador, char estatus) {
		this.id = id;
		this.competencia = competencia;
		this.familiarJugador = familiarJugador;
		this.estatus = estatus;
	}

	public Hospedaje(HospedajeId id, Competencia competencia,
			FamiliarJugador familiarJugador, char estatus,
			HospedajeJudador hospedajeJudador) {
		this.id = id;
		this.competencia = competencia;
		this.familiarJugador = familiarJugador;
		this.estatus = estatus;
		this.hospedajeJudador = hospedajeJudador;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoHospedaje", column = @Column(name = "codigo_hospedaje", nullable = false)),
			@AttributeOverride(name = "cedulaJugador", column = @Column(name = "cedula_jugador", nullable = false)),
			@AttributeOverride(name = "cedulaFamiliar", column = @Column(name = "cedula_familiar", nullable = false)) })
	public HospedajeId getId() {
		return this.id;
	}

	public void setId(HospedajeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_competencia", nullable = false)
	public Competencia getCompetencia() {
		return this.competencia;
	}

	public void setCompetencia(Competencia competencia) {
		this.competencia = competencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "cedula_jugador", referencedColumnName = "cedula_jugador", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "cedula_familiar", referencedColumnName = "cedula_familiar", nullable = false, insertable = false, updatable = false) })
	public FamiliarJugador getFamiliarJugador() {
		return this.familiarJugador;
	}

	public void setFamiliarJugador(FamiliarJugador familiarJugador) {
		this.familiarJugador = familiarJugador;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "hospedaje")
	public HospedajeJudador getHospedajeJudador() {
		return this.hospedajeJudador;
	}

	public void setHospedajeJudador(HospedajeJudador hospedajeJudador) {
		this.hospedajeJudador = hospedajeJudador;
	}

}
