package modelo;

// Generated 16-dic-2011 17:19:16 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HospedajeJugadorId generated by hbm2java
 */
@Embeddable
public class HospedajeJugadorId implements java.io.Serializable {

	private String codigoHospedaje;
	private String cedulaRif;
	private String cedulaFamiliar;

	public HospedajeJugadorId() {
	}

	public HospedajeJugadorId(String codigoHospedaje, String cedulaRif,
			String cedulaFamiliar) {
		this.codigoHospedaje = codigoHospedaje;
		this.cedulaRif = cedulaRif;
		this.cedulaFamiliar = cedulaFamiliar;
	}

	@Column(name = "codigo_hospedaje", nullable = false)
	public String getCodigoHospedaje() {
		return this.codigoHospedaje;
	}

	public void setCodigoHospedaje(String codigoHospedaje) {
		this.codigoHospedaje = codigoHospedaje;
	}

	@Column(name = "cedula_rif", nullable = false)
	public String getCedulaRif() {
		return this.cedulaRif;
	}

	public void setCedulaRif(String cedulaRif) {
		this.cedulaRif = cedulaRif;
	}

	@Column(name = "cedula_familiar", nullable = false)
	public String getCedulaFamiliar() {
		return this.cedulaFamiliar;
	}

	public void setCedulaFamiliar(String cedulaFamiliar) {
		this.cedulaFamiliar = cedulaFamiliar;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HospedajeJugadorId))
			return false;
		HospedajeJugadorId castOther = (HospedajeJugadorId) other;

		return ((this.getCodigoHospedaje() == castOther.getCodigoHospedaje()) || (this
				.getCodigoHospedaje() != null
				&& castOther.getCodigoHospedaje() != null && this
				.getCodigoHospedaje().equals(castOther.getCodigoHospedaje())))
				&& ((this.getCedulaRif() == castOther.getCedulaRif()) || (this
						.getCedulaRif() != null
						&& castOther.getCedulaRif() != null && this
						.getCedulaRif().equals(castOther.getCedulaRif())))
				&& ((this.getCedulaFamiliar() == castOther.getCedulaFamiliar()) || (this
						.getCedulaFamiliar() != null
						&& castOther.getCedulaFamiliar() != null && this
						.getCedulaFamiliar().equals(
								castOther.getCedulaFamiliar())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodigoHospedaje() == null ? 0 : this.getCodigoHospedaje()
						.hashCode());
		result = 37 * result
				+ (getCedulaRif() == null ? 0 : this.getCedulaRif().hashCode());
		result = 37
				* result
				+ (getCedulaFamiliar() == null ? 0 : this.getCedulaFamiliar()
						.hashCode());
		return result;
	}

}
