package modelo;

// Generated 13-dic-2011 21:15:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Importancia generated by hbm2java
 */
@Entity
@Table(name = "importancia")
public class Importancia implements java.io.Serializable {

	private String codigoImportancia;
	private String descripcion;
	private char estatus;
	private Set<RecaudoPorProceso> recaudoPorProcesos = new HashSet<RecaudoPorProceso>(
			0);

	public Importancia() {
	}

	public Importancia(String codigoImportancia, String descripcion,
			char estatus) {
		this.codigoImportancia = codigoImportancia;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	public Importancia(String codigoImportancia, String descripcion,
			char estatus, Set<RecaudoPorProceso> recaudoPorProcesos) {
		this.codigoImportancia = codigoImportancia;
		this.descripcion = descripcion;
		this.estatus = estatus;
		this.recaudoPorProcesos = recaudoPorProcesos;
	}

	@Id
	@Column(name = "codigo_importancia", unique = true, nullable = false)
	public String getCodigoImportancia() {
		return this.codigoImportancia;
	}

	public void setCodigoImportancia(String codigoImportancia) {
		this.codigoImportancia = codigoImportancia;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "importancia")
	public Set<RecaudoPorProceso> getRecaudoPorProcesos() {
		return this.recaudoPorProcesos;
	}

	public void setRecaudoPorProcesos(Set<RecaudoPorProceso> recaudoPorProcesos) {
		this.recaudoPorProcesos = recaudoPorProcesos;
	}

}
