package modelo;

// Generated 17/12/2011 10:20:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * IngresoFormaPago generated by hbm2java
 */
@Entity
@Table(name = "ingreso_forma_pago")
public class IngresoFormaPago implements java.io.Serializable {

	private String codigoDatoBasico;
	private DatoBasico datoBasicoByCodigoDatoBasico;
	private Ingreso ingreso;
	private DatoBasico datoBasicoByCodigoBanco;
	private String codigoFormaPago;
	private float monto;
	private String codigoTarjeta;
	private char estatus;

	public IngresoFormaPago() {
	}

	public IngresoFormaPago(DatoBasico datoBasicoByCodigoDatoBasico,
			Ingreso ingreso, DatoBasico datoBasicoByCodigoBanco,
			String codigoFormaPago, float monto, String codigoTarjeta,
			char estatus) {
		this.datoBasicoByCodigoDatoBasico = datoBasicoByCodigoDatoBasico;
		this.ingreso = ingreso;
		this.datoBasicoByCodigoBanco = datoBasicoByCodigoBanco;
		this.codigoFormaPago = codigoFormaPago;
		this.monto = monto;
		this.codigoTarjeta = codigoTarjeta;
		this.estatus = estatus;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "datoBasicoByCodigoDatoBasico"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "codigo_dato_basico", unique = true, nullable = false)
	public String getCodigoDatoBasico() {
		return this.codigoDatoBasico;
	}

	public void setCodigoDatoBasico(String codigoDatoBasico) {
		this.codigoDatoBasico = codigoDatoBasico;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public DatoBasico getDatoBasicoByCodigoDatoBasico() {
		return this.datoBasicoByCodigoDatoBasico;
	}

	public void setDatoBasicoByCodigoDatoBasico(
			DatoBasico datoBasicoByCodigoDatoBasico) {
		this.datoBasicoByCodigoDatoBasico = datoBasicoByCodigoDatoBasico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numero_documento", nullable = false)
	public Ingreso getIngreso() {
		return this.ingreso;
	}

	public void setIngreso(Ingreso ingreso) {
		this.ingreso = ingreso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_banco", nullable = false)
	public DatoBasico getDatoBasicoByCodigoBanco() {
		return this.datoBasicoByCodigoBanco;
	}

	public void setDatoBasicoByCodigoBanco(DatoBasico datoBasicoByCodigoBanco) {
		this.datoBasicoByCodigoBanco = datoBasicoByCodigoBanco;
	}

	@Column(name = "codigo_forma_pago", nullable = false)
	public String getCodigoFormaPago() {
		return this.codigoFormaPago;
	}

	public void setCodigoFormaPago(String codigoFormaPago) {
		this.codigoFormaPago = codigoFormaPago;
	}

	@Column(name = "monto", nullable = false, precision = 8, scale = 8)
	public float getMonto() {
		return this.monto;
	}

	public void setMonto(float monto) {
		this.monto = monto;
	}

	@Column(name = "codigo_tarjeta", nullable = false)
	public String getCodigoTarjeta() {
		return this.codigoTarjeta;
	}

	public void setCodigoTarjeta(String codigoTarjeta) {
		this.codigoTarjeta = codigoTarjeta;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

}
