package modelo;

// Generated 13-dic-2011 21:15:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Jugador generated by hbm2java
 */
@Entity
@Table(name = "jugador")
public class Jugador implements java.io.Serializable {

	private String cedulaJugador;
	private TallaCalzado tallaCalzado;
	private Pais pais;
	private TallaPantalon tallaPantalon;
	private Parroquia parroquia;
	private TallaCamisa tallaCamisa;
	private String codigoParroquiaNacimiento;
	private String primerNombre;
	private String segundoNombre;
	private String primerApellido;
	private String segundoApellido;
	private char genero;
	private Date fechaNacimiento;
	private String direccion;
	private String telefonoHabitacion;
	private String telefonoCelular;
	private String correoElectronico;
	private String twitter;
	private byte[] foto;
	private int numero;
	private String brazoLanzar;
	private String posicionBateo;
	private Date fechaIngreso;
	private char estatus;
	private String facebook;
	private double peso;
	private double altura;
	private Date fechaEgreso;
	private String tipoSangre;
	private Set<DatoMedico> datoMedicos = new HashSet<DatoMedico>(0);
	private Set<Roster> rosters = new HashSet<Roster>(0);
	private Set<ParticipantePlan> participantePlans = new HashSet<ParticipantePlan>(
			0);
	private Set<DatoDeportivo> datoDeportivos = new HashSet<DatoDeportivo>(0);
	private Set<DatoDeportivo> datoDeportivos_1 = new HashSet<DatoDeportivo>(0);
	private Set<FamiliarJugador> familiarJugadors = new HashSet<FamiliarJugador>(
			0);
	private Set<Roster> rosters_1 = new HashSet<Roster>(0);
	private Set<DatoAcademico> datoAcademicos = new HashSet<DatoAcademico>(0);
	private Set<DatoSocial> datoSocials = new HashSet<DatoSocial>(0);

	public Jugador() {
	}

	public Jugador(String cedulaJugador, TallaCalzado tallaCalzado, Pais pais,
			TallaPantalon tallaPantalon, Parroquia parroquia,
			TallaCamisa tallaCamisa, String codigoParroquiaNacimiento,
			String primerNombre, String primerApellido, char genero,
			Date fechaNacimiento, String direccion, byte[] foto, int numero,
			String brazoLanzar, String posicionBateo, Date fechaIngreso,
			char estatus, double peso, double altura, String tipoSangre) {
		this.cedulaJugador = cedulaJugador;
		this.tallaCalzado = tallaCalzado;
		this.pais = pais;
		this.tallaPantalon = tallaPantalon;
		this.parroquia = parroquia;
		this.tallaCamisa = tallaCamisa;
		this.codigoParroquiaNacimiento = codigoParroquiaNacimiento;
		this.primerNombre = primerNombre;
		this.primerApellido = primerApellido;
		this.genero = genero;
		this.fechaNacimiento = fechaNacimiento;
		this.direccion = direccion;
		this.foto = foto;
		this.numero = numero;
		this.brazoLanzar = brazoLanzar;
		this.posicionBateo = posicionBateo;
		this.fechaIngreso = fechaIngreso;
		this.estatus = estatus;
		this.peso = peso;
		this.altura = altura;
		this.tipoSangre = tipoSangre;
	}

	public Jugador(String cedulaJugador, TallaCalzado tallaCalzado, Pais pais,
			TallaPantalon tallaPantalon, Parroquia parroquia,
			TallaCamisa tallaCamisa, String codigoParroquiaNacimiento,
			String primerNombre, String segundoNombre, String primerApellido,
			String segundoApellido, char genero, Date fechaNacimiento,
			String direccion, String telefonoHabitacion,
			String telefonoCelular, String correoElectronico, String twitter,
			byte[] foto, int numero, String brazoLanzar, String posicionBateo,
			Date fechaIngreso, char estatus, String facebook, double peso,
			double altura, Date fechaEgreso, String tipoSangre,
			Set<DatoMedico> datoMedicos, Set<Roster> rosters,
			Set<ParticipantePlan> participantePlans,
			Set<DatoDeportivo> datoDeportivos,
			Set<DatoDeportivo> datoDeportivos_1,
			Set<FamiliarJugador> familiarJugadors, Set<Roster> rosters_1,
			Set<DatoAcademico> datoAcademicos, Set<DatoSocial> datoSocials) {
		this.cedulaJugador = cedulaJugador;
		this.tallaCalzado = tallaCalzado;
		this.pais = pais;
		this.tallaPantalon = tallaPantalon;
		this.parroquia = parroquia;
		this.tallaCamisa = tallaCamisa;
		this.codigoParroquiaNacimiento = codigoParroquiaNacimiento;
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.genero = genero;
		this.fechaNacimiento = fechaNacimiento;
		this.direccion = direccion;
		this.telefonoHabitacion = telefonoHabitacion;
		this.telefonoCelular = telefonoCelular;
		this.correoElectronico = correoElectronico;
		this.twitter = twitter;
		this.foto = foto;
		this.numero = numero;
		this.brazoLanzar = brazoLanzar;
		this.posicionBateo = posicionBateo;
		this.fechaIngreso = fechaIngreso;
		this.estatus = estatus;
		this.facebook = facebook;
		this.peso = peso;
		this.altura = altura;
		this.fechaEgreso = fechaEgreso;
		this.tipoSangre = tipoSangre;
		this.datoMedicos = datoMedicos;
		this.rosters = rosters;
		this.participantePlans = participantePlans;
		this.datoDeportivos = datoDeportivos;
		this.datoDeportivos_1 = datoDeportivos_1;
		this.familiarJugadors = familiarJugadors;
		this.rosters_1 = rosters_1;
		this.datoAcademicos = datoAcademicos;
		this.datoSocials = datoSocials;
	}

	@Id
	@Column(name = "cedula_jugador", unique = true, nullable = false)
	public String getCedulaJugador() {
		return this.cedulaJugador;
	}

	public void setCedulaJugador(String cedulaJugador) {
		this.cedulaJugador = cedulaJugador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_calzado", nullable = false)
	public TallaCalzado getTallaCalzado() {
		return this.tallaCalzado;
	}

	public void setTallaCalzado(TallaCalzado tallaCalzado) {
		this.tallaCalzado = tallaCalzado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_pais_nacimiento", nullable = false)
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_pantalon", nullable = false)
	public TallaPantalon getTallaPantalon() {
		return this.tallaPantalon;
	}

	public void setTallaPantalon(TallaPantalon tallaPantalon) {
		this.tallaPantalon = tallaPantalon;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_parroquia", nullable = false)
	public Parroquia getParroquia() {
		return this.parroquia;
	}

	public void setParroquia(Parroquia parroquia) {
		this.parroquia = parroquia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_camisa", nullable = false)
	public TallaCamisa getTallaCamisa() {
		return this.tallaCamisa;
	}

	public void setTallaCamisa(TallaCamisa tallaCamisa) {
		this.tallaCamisa = tallaCamisa;
	}

	@Column(name = "codigo_parroquia_nacimiento", nullable = false)
	public String getCodigoParroquiaNacimiento() {
		return this.codigoParroquiaNacimiento;
	}

	public void setCodigoParroquiaNacimiento(String codigoParroquiaNacimiento) {
		this.codigoParroquiaNacimiento = codigoParroquiaNacimiento;
	}

	@Column(name = "primer_nombre", nullable = false)
	public String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(String primerNombre) {
		this.primerNombre = primerNombre;
	}

	@Column(name = "segundo_nombre")
	public String getSegundoNombre() {
		return this.segundoNombre;
	}

	public void setSegundoNombre(String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	@Column(name = "primer_apellido", nullable = false)
	public String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}

	@Column(name = "segundo_apellido")
	public String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	@Column(name = "genero", nullable = false, length = 1)
	public char getGenero() {
		return this.genero;
	}

	public void setGenero(char genero) {
		this.genero = genero;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nacimiento", nullable = false, length = 13)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "direccion", nullable = false)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefono_habitacion")
	public String getTelefonoHabitacion() {
		return this.telefonoHabitacion;
	}

	public void setTelefonoHabitacion(String telefonoHabitacion) {
		this.telefonoHabitacion = telefonoHabitacion;
	}

	@Column(name = "telefono_celular")
	public String getTelefonoCelular() {
		return this.telefonoCelular;
	}

	public void setTelefonoCelular(String telefonoCelular) {
		this.telefonoCelular = telefonoCelular;
	}

	@Column(name = "correo_electronico")
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@Column(name = "twitter")
	public String getTwitter() {
		return this.twitter;
	}

	public void setTwitter(String twitter) {
		this.twitter = twitter;
	}

	@Column(name = "foto", nullable = false)
	public byte[] getFoto() {
		return this.foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	@Column(name = "numero", nullable = false)
	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	@Column(name = "brazo_lanzar", nullable = false)
	public String getBrazoLanzar() {
		return this.brazoLanzar;
	}

	public void setBrazoLanzar(String brazoLanzar) {
		this.brazoLanzar = brazoLanzar;
	}

	@Column(name = "posicion_bateo", nullable = false)
	public String getPosicionBateo() {
		return this.posicionBateo;
	}

	public void setPosicionBateo(String posicionBateo) {
		this.posicionBateo = posicionBateo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ingreso", nullable = false, length = 13)
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Column(name = "facebook")
	public String getFacebook() {
		return this.facebook;
	}

	public void setFacebook(String facebook) {
		this.facebook = facebook;
	}

	@Column(name = "peso", nullable = false, precision = 17, scale = 17)
	public double getPeso() {
		return this.peso;
	}

	public void setPeso(double peso) {
		this.peso = peso;
	}

	@Column(name = "altura", nullable = false, precision = 17, scale = 17)
	public double getAltura() {
		return this.altura;
	}

	public void setAltura(double altura) {
		this.altura = altura;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_egreso", length = 13)
	public Date getFechaEgreso() {
		return this.fechaEgreso;
	}

	public void setFechaEgreso(Date fechaEgreso) {
		this.fechaEgreso = fechaEgreso;
	}

	@Column(name = "tipo_sangre", nullable = false)
	public String getTipoSangre() {
		return this.tipoSangre;
	}

	public void setTipoSangre(String tipoSangre) {
		this.tipoSangre = tipoSangre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jugador")
	public Set<DatoMedico> getDatoMedicos() {
		return this.datoMedicos;
	}

	public void setDatoMedicos(Set<DatoMedico> datoMedicos) {
		this.datoMedicos = datoMedicos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jugador")
	public Set<Roster> getRosters() {
		return this.rosters;
	}

	public void setRosters(Set<Roster> rosters) {
		this.rosters = rosters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jugador")
	public Set<ParticipantePlan> getParticipantePlans() {
		return this.participantePlans;
	}

	public void setParticipantePlans(Set<ParticipantePlan> participantePlans) {
		this.participantePlans = participantePlans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jugador")
	public Set<DatoDeportivo> getDatoDeportivos() {
		return this.datoDeportivos;
	}

	public void setDatoDeportivos(Set<DatoDeportivo> datoDeportivos) {
		this.datoDeportivos = datoDeportivos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jugador")
	public Set<DatoDeportivo> getDatoDeportivos_1() {
		return this.datoDeportivos_1;
	}

	public void setDatoDeportivos_1(Set<DatoDeportivo> datoDeportivos_1) {
		this.datoDeportivos_1 = datoDeportivos_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jugador")
	public Set<FamiliarJugador> getFamiliarJugadors() {
		return this.familiarJugadors;
	}

	public void setFamiliarJugadors(Set<FamiliarJugador> familiarJugadors) {
		this.familiarJugadors = familiarJugadors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jugador")
	public Set<Roster> getRosters_1() {
		return this.rosters_1;
	}

	public void setRosters_1(Set<Roster> rosters_1) {
		this.rosters_1 = rosters_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jugador")
	public Set<DatoAcademico> getDatoAcademicos() {
		return this.datoAcademicos;
	}

	public void setDatoAcademicos(Set<DatoAcademico> datoAcademicos) {
		this.datoAcademicos = datoAcademicos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jugador")
	public Set<DatoSocial> getDatoSocials() {
		return this.datoSocials;
	}

	public void setDatoSocials(Set<DatoSocial> datoSocials) {
		this.datoSocials = datoSocials;
	}

}
