package modelo;

// Generated 09/01/2012 10:19:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JugadorRefuerzo generated by hbm2java
 */
@Entity
@Table(name = "jugador_refuerzo", schema = "public")
public class JugadorRefuerzo implements java.io.Serializable {

	private String cedula;
	private EquipoCompetencia equipoCompetencia;
	private String nombre;
	private Set<RosterCompetencia> rosterCompetencias = new HashSet<RosterCompetencia>(
			0);

	public JugadorRefuerzo() {
	}

	public JugadorRefuerzo(String cedula, EquipoCompetencia equipoCompetencia,
			String nombre) {
		this.cedula = cedula;
		this.equipoCompetencia = equipoCompetencia;
		this.nombre = nombre;
	}

	public JugadorRefuerzo(String cedula, EquipoCompetencia equipoCompetencia,
			String nombre, Set<RosterCompetencia> rosterCompetencias) {
		this.cedula = cedula;
		this.equipoCompetencia = equipoCompetencia;
		this.nombre = nombre;
		this.rosterCompetencias = rosterCompetencias;
	}

	@Id
	@Column(name = "cedula", unique = true, nullable = false)
	public String getCedula() {
		return this.cedula;
	}

	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_equipo_competencia", nullable = false)
	public EquipoCompetencia getEquipoCompetencia() {
		return this.equipoCompetencia;
	}

	public void setEquipoCompetencia(EquipoCompetencia equipoCompetencia) {
		this.equipoCompetencia = equipoCompetencia;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "jugador_refuerzo_roster_competencia", schema = "public", joinColumns = { @JoinColumn(name = "cedula", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "codigo_roster_competencia", nullable = false, updatable = false) })
	public Set<RosterCompetencia> getRosterCompetencias() {
		return this.rosterCompetencias;
	}

	public void setRosterCompetencias(Set<RosterCompetencia> rosterCompetencias) {
		this.rosterCompetencias = rosterCompetencias;
	}

}
