package modelo;

// Generated 13-dic-2011 21:15:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Liga generated by hbm2java
 */
@Entity
@Table(name = "liga")
public class Liga implements java.io.Serializable {

	private String codigoLiga;
	private String nombre;
	private byte[] logo;
	private Set<LigaCategoria> ligaCategorias = new HashSet<LigaCategoria>(0);
	private Set<LigaCategoria> ligaCategorias_1 = new HashSet<LigaCategoria>(0);

	public Liga() {
	}

	public Liga(String codigoLiga, String nombre, byte[] logo) {
		this.codigoLiga = codigoLiga;
		this.nombre = nombre;
		this.logo = logo;
	}

	public Liga(String codigoLiga, String nombre, byte[] logo,
			Set<LigaCategoria> ligaCategorias,
			Set<LigaCategoria> ligaCategorias_1) {
		this.codigoLiga = codigoLiga;
		this.nombre = nombre;
		this.logo = logo;
		this.ligaCategorias = ligaCategorias;
		this.ligaCategorias_1 = ligaCategorias_1;
	}

	@Id
	@Column(name = "codigo_liga", unique = true, nullable = false)
	public String getCodigoLiga() {
		return this.codigoLiga;
	}

	public void setCodigoLiga(String codigoLiga) {
		this.codigoLiga = codigoLiga;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "logo", nullable = false)
	public byte[] getLogo() {
		return this.logo;
	}

	public void setLogo(byte[] logo) {
		this.logo = logo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "liga")
	public Set<LigaCategoria> getLigaCategorias() {
		return this.ligaCategorias;
	}

	public void setLigaCategorias(Set<LigaCategoria> ligaCategorias) {
		this.ligaCategorias = ligaCategorias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "liga")
	public Set<LigaCategoria> getLigaCategorias_1() {
		return this.ligaCategorias_1;
	}

	public void setLigaCategorias_1(Set<LigaCategoria> ligaCategorias_1) {
		this.ligaCategorias_1 = ligaCategorias_1;
	}

}
