package modelo;

// Generated 13-dic-2011 21:15:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LigaCategoria generated by hbm2java
 */
@Entity
@Table(name = "liga_categoria")
public class LigaCategoria implements java.io.Serializable {

	private LigaCategoriaId id;
	private Categoria categoria;
	private Liga liga;
	private Character estatus;

	public LigaCategoria() {
	}

	public LigaCategoria(LigaCategoriaId id, Categoria categoria, Liga liga) {
		this.id = id;
		this.categoria = categoria;
		this.liga = liga;
	}

	public LigaCategoria(LigaCategoriaId id, Categoria categoria, Liga liga,
			Character estatus) {
		this.id = id;
		this.categoria = categoria;
		this.liga = liga;
		this.estatus = estatus;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoLiga", column = @Column(name = "codigo_liga", nullable = false)),
			@AttributeOverride(name = "codigoCategoria", column = @Column(name = "codigo_categoria", nullable = false)) })
	public LigaCategoriaId getId() {
		return this.id;
	}

	public void setId(LigaCategoriaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_categoria", nullable = false, insertable = false, updatable = false)
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_liga", nullable = false, insertable = false, updatable = false)
	public Liga getLiga() {
		return this.liga;
	}

	public void setLiga(Liga liga) {
		this.liga = liga;
	}

	@Column(name = "estatus", length = 1)
	public Character getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Character estatus) {
		this.estatus = estatus;
	}

}
