package modelo;

// Generated 16-dic-2011 17:19:16 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LogroPorJugadorId generated by hbm2java
 */
@Embeddable
public class LogroPorJugadorId implements java.io.Serializable {

	private String codigoCompetencia;
	private String cedulaRif;
	private String codigoLogro;

	public LogroPorJugadorId() {
	}

	public LogroPorJugadorId(String codigoCompetencia, String cedulaRif,
			String codigoLogro) {
		this.codigoCompetencia = codigoCompetencia;
		this.cedulaRif = cedulaRif;
		this.codigoLogro = codigoLogro;
	}

	@Column(name = "codigo_competencia", nullable = false)
	public String getCodigoCompetencia() {
		return this.codigoCompetencia;
	}

	public void setCodigoCompetencia(String codigoCompetencia) {
		this.codigoCompetencia = codigoCompetencia;
	}

	@Column(name = "cedula_rif", nullable = false)
	public String getCedulaRif() {
		return this.cedulaRif;
	}

	public void setCedulaRif(String cedulaRif) {
		this.cedulaRif = cedulaRif;
	}

	@Column(name = "codigo_logro", nullable = false)
	public String getCodigoLogro() {
		return this.codigoLogro;
	}

	public void setCodigoLogro(String codigoLogro) {
		this.codigoLogro = codigoLogro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LogroPorJugadorId))
			return false;
		LogroPorJugadorId castOther = (LogroPorJugadorId) other;

		return ((this.getCodigoCompetencia() == castOther
				.getCodigoCompetencia()) || (this.getCodigoCompetencia() != null
				&& castOther.getCodigoCompetencia() != null && this
				.getCodigoCompetencia()
				.equals(castOther.getCodigoCompetencia())))
				&& ((this.getCedulaRif() == castOther.getCedulaRif()) || (this
						.getCedulaRif() != null
						&& castOther.getCedulaRif() != null && this
						.getCedulaRif().equals(castOther.getCedulaRif())))
				&& ((this.getCodigoLogro() == castOther.getCodigoLogro()) || (this
						.getCodigoLogro() != null
						&& castOther.getCodigoLogro() != null && this
						.getCodigoLogro().equals(castOther.getCodigoLogro())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodigoCompetencia() == null ? 0 : this
						.getCodigoCompetencia().hashCode());
		result = 37 * result
				+ (getCedulaRif() == null ? 0 : this.getCedulaRif().hashCode());
		result = 37
				* result
				+ (getCodigoLogro() == null ? 0 : this.getCodigoLogro()
						.hashCode());
		return result;
	}

}
