package modelo;

// Generated 16-dic-2011 17:19:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ParticipantePlan generated by hbm2java
 */
@Entity
@Table(name = "participante_plan")
public class ParticipantePlan implements java.io.Serializable {

	private String codigoParticipante;
	private TallaPorIndumentaria tallaPorIndumentaria;
	private Categoria categoria;
	private Jugador jugador;
	private String tipoJugador;
	private String cedulaJugador;
	private String nombre;
	private String apellido;
	private Date fechaNacimiento;
	private char estatus;
	private Set<PlanJugador> planJugadors = new HashSet<PlanJugador>(0);

	public ParticipantePlan() {
	}

	public ParticipantePlan(String codigoParticipante,
			TallaPorIndumentaria tallaPorIndumentaria, Categoria categoria,
			Jugador jugador, String tipoJugador, String cedulaJugador,
			String nombre, String apellido, Date fechaNacimiento, char estatus) {
		this.codigoParticipante = codigoParticipante;
		this.tallaPorIndumentaria = tallaPorIndumentaria;
		this.categoria = categoria;
		this.jugador = jugador;
		this.tipoJugador = tipoJugador;
		this.cedulaJugador = cedulaJugador;
		this.nombre = nombre;
		this.apellido = apellido;
		this.fechaNacimiento = fechaNacimiento;
		this.estatus = estatus;
	}

	public ParticipantePlan(String codigoParticipante,
			TallaPorIndumentaria tallaPorIndumentaria, Categoria categoria,
			Jugador jugador, String tipoJugador, String cedulaJugador,
			String nombre, String apellido, Date fechaNacimiento, char estatus,
			Set<PlanJugador> planJugadors) {
		this.codigoParticipante = codigoParticipante;
		this.tallaPorIndumentaria = tallaPorIndumentaria;
		this.categoria = categoria;
		this.jugador = jugador;
		this.tipoJugador = tipoJugador;
		this.cedulaJugador = cedulaJugador;
		this.nombre = nombre;
		this.apellido = apellido;
		this.fechaNacimiento = fechaNacimiento;
		this.estatus = estatus;
		this.planJugadors = planJugadors;
	}

	@Id
	@Column(name = "codigo_participante", unique = true, nullable = false)
	public String getCodigoParticipante() {
		return this.codigoParticipante;
	}

	public void setCodigoParticipante(String codigoParticipante) {
		this.codigoParticipante = codigoParticipante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_talla_indumentaria", nullable = false)
	public TallaPorIndumentaria getTallaPorIndumentaria() {
		return this.tallaPorIndumentaria;
	}

	public void setTallaPorIndumentaria(
			TallaPorIndumentaria tallaPorIndumentaria) {
		this.tallaPorIndumentaria = tallaPorIndumentaria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_categoria", nullable = false)
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cedula_rif", nullable = false)
	public Jugador getJugador() {
		return this.jugador;
	}

	public void setJugador(Jugador jugador) {
		this.jugador = jugador;
	}

	@Column(name = "tipo_jugador", nullable = false)
	public String getTipoJugador() {
		return this.tipoJugador;
	}

	public void setTipoJugador(String tipoJugador) {
		this.tipoJugador = tipoJugador;
	}

	@Column(name = "cedula_jugador", nullable = false)
	public String getCedulaJugador() {
		return this.cedulaJugador;
	}

	public void setCedulaJugador(String cedulaJugador) {
		this.cedulaJugador = cedulaJugador;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", nullable = false)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nacimiento", nullable = false, length = 13)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "participantePlan")
	public Set<PlanJugador> getPlanJugadors() {
		return this.planJugadors;
	}

	public void setPlanJugadors(Set<PlanJugador> planJugadors) {
		this.planJugadors = planJugadors;
	}

}
