package modelo;

// Generated 13-dic-2011 21:15:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlanVacacional generated by hbm2java
 */
@Entity
@Table(name = "plan_vacacional")
public class PlanVacacional implements java.io.Serializable {

	private String codigoPlan;
	private Date fechaInicio;
	private Date fechaFin;
	private int cupo;
	private char estatus;
	private Set<PlanJugador> planJugadors = new HashSet<PlanJugador>(0);

	public PlanVacacional() {
	}

	public PlanVacacional(String codigoPlan, Date fechaInicio, Date fechaFin,
			int cupo, char estatus) {
		this.codigoPlan = codigoPlan;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.cupo = cupo;
		this.estatus = estatus;
	}

	public PlanVacacional(String codigoPlan, Date fechaInicio, Date fechaFin,
			int cupo, char estatus, Set<PlanJugador> planJugadors) {
		this.codigoPlan = codigoPlan;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.cupo = cupo;
		this.estatus = estatus;
		this.planJugadors = planJugadors;
	}

	@Id
	@Column(name = "codigo_plan", unique = true, nullable = false)
	public String getCodigoPlan() {
		return this.codigoPlan;
	}

	public void setCodigoPlan(String codigoPlan) {
		this.codigoPlan = codigoPlan;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", nullable = false, length = 13)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", nullable = false, length = 13)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "cupo", nullable = false)
	public int getCupo() {
		return this.cupo;
	}

	public void setCupo(int cupo) {
		this.cupo = cupo;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planVacacional")
	public Set<PlanJugador> getPlanJugadors() {
		return this.planJugadors;
	}

	public void setPlanJugadors(Set<PlanJugador> planJugadors) {
		this.planJugadors = planJugadors;
	}

}
