package modelo;

// Generated 17/12/2011 10:20:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PlanJugador generated by hbm2java
 */
@Entity
@Table(name = "plan_jugador")
public class PlanJugador implements java.io.Serializable {

	private PlanJugadorId id;
	private ParticipantePlan participantePlan;
	private PlanVacacional planVacacional;
	private char estatus;

	public PlanJugador() {
	}

	public PlanJugador(PlanJugadorId id, ParticipantePlan participantePlan,
			PlanVacacional planVacacional, char estatus) {
		this.id = id;
		this.participantePlan = participantePlan;
		this.planVacacional = planVacacional;
		this.estatus = estatus;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoPlan", column = @Column(name = "codigo_plan", nullable = false)),
			@AttributeOverride(name = "codigoParticipante", column = @Column(name = "codigo_participante", nullable = false)) })
	public PlanJugadorId getId() {
		return this.id;
	}

	public void setId(PlanJugadorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_participante", nullable = false, insertable = false, updatable = false)
	public ParticipantePlan getParticipantePlan() {
		return this.participantePlan;
	}

	public void setParticipantePlan(ParticipantePlan participantePlan) {
		this.participantePlan = participantePlan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_plan", nullable = false, insertable = false, updatable = false)
	public PlanVacacional getPlanVacacional() {
		return this.planVacacional;
	}

	public void setPlanVacacional(PlanVacacional planVacacional) {
		this.planVacacional = planVacacional;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

}
