package modelo;

// Generated 13-dic-2011 23:21:03 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proceso generated by hbm2java
 */
@Entity
@Table(name = "proceso")
public class Proceso implements java.io.Serializable {

	private String codigoProceso;
	private String nombre;
	private char estatus;
	private Set<RecaudoPorProceso> recaudoPorProcesos = new HashSet<RecaudoPorProceso>(
			0);

	public Proceso() {
	}

	public Proceso(String codigoProceso, String nombre, char estatus) {
		this.codigoProceso = codigoProceso;
		this.nombre = nombre;
		this.estatus = estatus;
	}

	public Proceso(String codigoProceso, String nombre, char estatus,
			Set<RecaudoPorProceso> recaudoPorProcesos) {
		this.codigoProceso = codigoProceso;
		this.nombre = nombre;
		this.estatus = estatus;
		this.recaudoPorProcesos = recaudoPorProcesos;
	}

	@Id
	@Column(name = "codigo_proceso", unique = true, nullable = false)
	public String getCodigoProceso() {
		return this.codigoProceso;
	}

	public void setCodigoProceso(String codigoProceso) {
		this.codigoProceso = codigoProceso;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proceso")
	public Set<RecaudoPorProceso> getRecaudoPorProcesos() {
		return this.recaudoPorProcesos;
	}

	public void setRecaudoPorProcesos(Set<RecaudoPorProceso> recaudoPorProcesos) {
		this.recaudoPorProcesos = recaudoPorProcesos;
	}

}
