package modelo;

// Generated 13-dic-2011 21:15:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Representante generated by hbm2java
 */
@Entity
@Table(name = "representante")
public class Representante implements java.io.Serializable {

	private RepresentanteId id;
	private FamiliarJugador familiarJugador;
	private Date fechaAsignacion;
	private String codigoParentesco;
	private Date fechaRetiro;

	public Representante() {
	}

	public Representante(FamiliarJugador familiarJugador, Date fechaAsignacion,
			String codigoParentesco, Date fechaRetiro) {
		this.familiarJugador = familiarJugador;
		this.fechaAsignacion = fechaAsignacion;
		this.codigoParentesco = codigoParentesco;
		this.fechaRetiro = fechaRetiro;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cedulaJugador", column = @Column(name = "cedula_jugador", nullable = false)),
			@AttributeOverride(name = "cedulaFamiliar", column = @Column(name = "cedula_familiar", nullable = false)) })
	public RepresentanteId getId() {
		return this.id;
	}

	public void setId(RepresentanteId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public FamiliarJugador getFamiliarJugador() {
		return this.familiarJugador;
	}

	public void setFamiliarJugador(FamiliarJugador familiarJugador) {
		this.familiarJugador = familiarJugador;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_asignacion", nullable = false, length = 13)
	public Date getFechaAsignacion() {
		return this.fechaAsignacion;
	}

	public void setFechaAsignacion(Date fechaAsignacion) {
		this.fechaAsignacion = fechaAsignacion;
	}

	@Column(name = "codigo_parentesco", nullable = false)
	public String getCodigoParentesco() {
		return this.codigoParentesco;
	}

	public void setCodigoParentesco(String codigoParentesco) {
		this.codigoParentesco = codigoParentesco;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_retiro", nullable = false, length = 13)
	public Date getFechaRetiro() {
		return this.fechaRetiro;
	}

	public void setFechaRetiro(Date fechaRetiro) {
		this.fechaRetiro = fechaRetiro;
	}

}
