package modelo;

// Generated 13-dic-2011 23:21:03 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TallaCalzado generated by hbm2java
 */
@Entity
@Table(name = "talla_calzado")
public class TallaCalzado implements java.io.Serializable {

	private String codigoCalzado;
	private String talla;
	private char estatus;
	private Set<Jugador> jugadors = new HashSet<Jugador>(0);

	public TallaCalzado() {
	}

	public TallaCalzado(String codigoCalzado, String talla, char estatus) {
		this.codigoCalzado = codigoCalzado;
		this.talla = talla;
		this.estatus = estatus;
	}

	public TallaCalzado(String codigoCalzado, String talla, char estatus,
			Set<Jugador> jugadors) {
		this.codigoCalzado = codigoCalzado;
		this.talla = talla;
		this.estatus = estatus;
		this.jugadors = jugadors;
	}

	@Id
	@Column(name = "codigo_calzado", unique = true, nullable = false)
	public String getCodigoCalzado() {
		return this.codigoCalzado;
	}

	public void setCodigoCalzado(String codigoCalzado) {
		this.codigoCalzado = codigoCalzado;
	}

	@Column(name = "talla", nullable = false)
	public String getTalla() {
		return this.talla;
	}

	public void setTalla(String talla) {
		this.talla = talla;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tallaCalzado")
	public Set<Jugador> getJugadors() {
		return this.jugadors;
	}

	public void setJugadors(Set<Jugador> jugadors) {
		this.jugadors = jugadors;
	}

}
