package modelo;

// Generated 16-dic-2011 17:19:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TallaPorIndumentaria generated by hbm2java
 */
@Entity
@Table(name = "talla_por_indumentaria")
public class TallaPorIndumentaria implements java.io.Serializable {

	private String codigoTallaIndumentaria;
	private DatoBasico datoBasicoByCodigoTalla;
	private DatoBasico datoBasicoByCodigoIndumentaria;
	private char estatus;
	private Set<TallaPorJugador> tallaPorJugadors = new HashSet<TallaPorJugador>(
			0);
	private Set<ParticipantePlan> participantePlans = new HashSet<ParticipantePlan>(
			0);

	public TallaPorIndumentaria() {
	}

	public TallaPorIndumentaria(String codigoTallaIndumentaria,
			DatoBasico datoBasicoByCodigoTalla,
			DatoBasico datoBasicoByCodigoIndumentaria, char estatus) {
		this.codigoTallaIndumentaria = codigoTallaIndumentaria;
		this.datoBasicoByCodigoTalla = datoBasicoByCodigoTalla;
		this.datoBasicoByCodigoIndumentaria = datoBasicoByCodigoIndumentaria;
		this.estatus = estatus;
	}

	public TallaPorIndumentaria(String codigoTallaIndumentaria,
			DatoBasico datoBasicoByCodigoTalla,
			DatoBasico datoBasicoByCodigoIndumentaria, char estatus,
			Set<TallaPorJugador> tallaPorJugadors,
			Set<ParticipantePlan> participantePlans) {
		this.codigoTallaIndumentaria = codigoTallaIndumentaria;
		this.datoBasicoByCodigoTalla = datoBasicoByCodigoTalla;
		this.datoBasicoByCodigoIndumentaria = datoBasicoByCodigoIndumentaria;
		this.estatus = estatus;
		this.tallaPorJugadors = tallaPorJugadors;
		this.participantePlans = participantePlans;
	}

	@Id
	@Column(name = "codigo_talla_indumentaria", unique = true, nullable = false)
	public String getCodigoTallaIndumentaria() {
		return this.codigoTallaIndumentaria;
	}

	public void setCodigoTallaIndumentaria(String codigoTallaIndumentaria) {
		this.codigoTallaIndumentaria = codigoTallaIndumentaria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_talla", nullable = false)
	public DatoBasico getDatoBasicoByCodigoTalla() {
		return this.datoBasicoByCodigoTalla;
	}

	public void setDatoBasicoByCodigoTalla(DatoBasico datoBasicoByCodigoTalla) {
		this.datoBasicoByCodigoTalla = datoBasicoByCodigoTalla;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_indumentaria", nullable = false)
	public DatoBasico getDatoBasicoByCodigoIndumentaria() {
		return this.datoBasicoByCodigoIndumentaria;
	}

	public void setDatoBasicoByCodigoIndumentaria(
			DatoBasico datoBasicoByCodigoIndumentaria) {
		this.datoBasicoByCodigoIndumentaria = datoBasicoByCodigoIndumentaria;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tallaPorIndumentaria")
	public Set<TallaPorJugador> getTallaPorJugadors() {
		return this.tallaPorJugadors;
	}

	public void setTallaPorJugadors(Set<TallaPorJugador> tallaPorJugadors) {
		this.tallaPorJugadors = tallaPorJugadors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tallaPorIndumentaria")
	public Set<ParticipantePlan> getParticipantePlans() {
		return this.participantePlans;
	}

	public void setParticipantePlans(Set<ParticipantePlan> participantePlans) {
		this.participantePlans = participantePlans;
	}

}
