package modelo;

// Generated 13-dic-2011 23:21:03 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TallaCamisa generated by hbm2java
 */
@Entity
@Table(name = "talla_camisa")
public class TallaCamisa implements java.io.Serializable {

	private String codigoCamisa;
	private String talla;
	private char estatus;
	private Set<Jugador> jugadors = new HashSet<Jugador>(0);

	public TallaCamisa() {
	}

	public TallaCamisa(String codigoCamisa, String talla, char estatus) {
		this.codigoCamisa = codigoCamisa;
		this.talla = talla;
		this.estatus = estatus;
	}

	public TallaCamisa(String codigoCamisa, String talla, char estatus,
			Set<Jugador> jugadors) {
		this.codigoCamisa = codigoCamisa;
		this.talla = talla;
		this.estatus = estatus;
		this.jugadors = jugadors;
	}

	@Id
	@Column(name = "codigo_camisa", unique = true, nullable = false)
	public String getCodigoCamisa() {
		return this.codigoCamisa;
	}

	public void setCodigoCamisa(String codigoCamisa) {
		this.codigoCamisa = codigoCamisa;
	}

	@Column(name = "talla", nullable = false)
	public String getTalla() {
		return this.talla;
	}

	public void setTalla(String talla) {
		this.talla = talla;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tallaCamisa")
	public Set<Jugador> getJugadors() {
		return this.jugadors;
	}

	public void setJugadors(Set<Jugador> jugadors) {
		this.jugadors = jugadors;
	}

}
