package modelo;

// Generated 17/12/2011 10:20:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Umpire generated by hbm2java
 */
@Entity
@Table(name = "umpire")
public class Umpire implements java.io.Serializable {

	private String codigoUmpire;
	private String nombre;
	private Set<Juego> juegos = new HashSet<Juego>(0);

	public Umpire() {
	}

	public Umpire(String codigoUmpire, String nombre) {
		this.codigoUmpire = codigoUmpire;
		this.nombre = nombre;
	}

	public Umpire(String codigoUmpire, String nombre, Set<Juego> juegos) {
		this.codigoUmpire = codigoUmpire;
		this.nombre = nombre;
		this.juegos = juegos;
	}

	@Id
	@Column(name = "codigo_umpire", unique = true, nullable = false)
	public String getCodigoUmpire() {
		return this.codigoUmpire;
	}

	public void setCodigoUmpire(String codigoUmpire) {
		this.codigoUmpire = codigoUmpire;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "umpire_juego", joinColumns = { @JoinColumn(name = "codigo_umpire", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "codigo_juego", nullable = false, updatable = false) })
	public Set<Juego> getJuegos() {
		return this.juegos;
	}

	public void setJuegos(Set<Juego> juegos) {
		this.juegos = juegos;
	}

}
